apiVersion: v1
kind: PersistentVolume            # Create a PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                       # hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/tmp/mysql"
  persistentVolumeReclaimPolicy: Retain  # Retain the PersistentVolume even after PersistentVolumeClaim is deleted. The volume is considered “released”. But it is not yet available for another claim because the previous claimant’s data remains on the volume. 
---    

apiVersion: v1
kind: PersistentVolumeClaim        # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                          # Claim name and labels
  name: mysql-pvc
spec:                              # Access mode and resource limits
  accessModes:
    - ReadWriteOnce                # ReadWriteOnce means the volume can be mounted as read-write by a single Node
  resources:
    requests:
      storage: 500Mi
---

apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource 
metadata:
  name: mysql         # Name of the resource
  labels:                         # Labels that will be applied to the resource
    app: mysql
spec:
  ports:
    - port: 3306
  selector:                       # Selects any Pod with labels `app=social-login-app,tier=mysql`
    app: mysql
---

apiVersion: apps/v1
kind: Deployment                    # Type of the kubernetes resource
metadata:
  name: mysql          # Name of the deployment
  labels:                           # Labels applied to this deployment 
    app: mysql
spec:
  selector:
    matchLabels:                    # This deployment applies to the Pods matching the specified labels
      app: mysql
  strategy:
    type: Recreate
  template:                         # Template for the Pods in this deployment
    metadata:
      labels:                       # Labels to be applied to the Pods in this deployment
        app: mysql
    spec:                           # The spec for the containers that will be run inside the Pods in this deployment
      containers:
      - image: mysql           # The container image
        name: mysql
        env:                        # Environment variables passed to the container 
        - name: MYSQL_ROOT_PASSWORD 
          value: root
        - name: MYSQL_DATABASE
          value: demo
        ports:
        - containerPort: 3306        # The port that the container exposes       
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  # This name should match the name specified in `volumes.name`
          mountPath: /var/lib/mysql
      volumes:                       # A PersistentVolume is mounted as a volume to the Pod  
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
# Deployment Spring Boot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: nouran10/myapp-backend
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/demo
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: spring.jpa.database-platform
              value: org.hibernate.dialect.MySQL8Dialect
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_MVC_CORS_MAPPING
              value: /**
            - name: SPRING_MVC_CORS_ALLOWED_METHODS
              value: GET,POST,PUT,DELETE
            - name: SPRING_MVC_CORS_ALLOWED_HEADERS
              value: "*"
---
# Service Spring Boot
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
# Deployment Angular
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: nouran10/myapp-frontend
          ports:
            - containerPort: 80
          command: ["nginx", "-g", "daemon off;"] # Angular doit rester en écoute
---
# Service Angular
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000