---
- hosts: master
  become: yes

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf  

  tasks:

  - name: Deploy pvc
    command: kubectl apply -f /home/ubuntu/Dep/k8s/pvc.yaml

  - name: Deploy mysql
    command: kubectl apply -f /home/ubuntu/Dep/k8s/mysql-deploy.yaml

  - name: service mysql
    command:  kubectl apply -f /home/ubuntu/Dep/k8s/mysql-service.yaml

  - name: Deploy frontend
    command: kubectl apply -f /home/ubuntu/Dep/k8s/deploy-angular.yaml

  - name: service frontend
    command:  kubectl apply -f /home/ubuntu/Dep/k8s/angular-svc.yaml

  - name: Deploy Backend
    command: kubectl apply -f /home/ubuntu/Dep/k8s/deploy-spring.yaml

  - name: service beckend
    command:  kubectl apply -f /home/ubuntu/Dep/k8s/service-backend.yaml

  - name: exposition avec ingress
    become: yes 
    command: kubectl apply -f  /home/ubuntu/Dep/ingress.yaml 
