name: my first workflows

on: push

jobs: 
    first_job: 
        runs-on: ubuntu:latest
        steps: 
        - name: welcome message
          run: echo "hello from github job "
        - name: List files 
          run: ls
        - name: read file
          run: cat readme.md